#%RAML 1.0 DataType
type: object
properties:
  token:
    type: string
    description: the token obteined from email.
  password:
    type: string
    minLength: 6
    maxLength: 150
    description: the new user password.
examples:
  -
    token: 'bhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9'
    password: 'secret'
